version: "3.8"

services:
  mariadb:
    image: mariadb:lts-noble
    container_name: mariadb-db
    restart: always
    networks:
      - mi-red-db
    ports:
      - "3307:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      # - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - ./data/mariadb:/var/lib/mysql

  phpmyadminMariaDB:
    image: phpmyadmin:5.2.2-apache
    container_name: phpmyadmin-db
    restart: always
    networks:
      - mi-red-db
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=${MARIADB_ROOT_PASSWORD}

networks:
  mi-red-db:
    driver: bridge
