-- MySQL Script generated by MySQL Workbench
-- Sat May  3 16:42:36 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cuadrantes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `ci_sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ci_sessions` (
  `session_id` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '0',
  `ip_address` VARCHAR(16) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '0',
  `user_agent` VARCHAR(150) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `last_activity` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `user_data` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  PRIMARY KEY (`session_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `login_attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login_attempts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `login` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `user_autologin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_autologin` (
  `key_id` CHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `user_id` INT(11) NOT NULL DEFAULT '0',
  `user_agent` VARCHAR(150) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `last_ip` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `last_login` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`key_id`, `user_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `user_profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_profiles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `country` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `website` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `email` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `activated` TINYINT(1) NOT NULL DEFAULT '1',
  `banned` TINYINT(1) NOT NULL DEFAULT '0',
  `ban_reason` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `new_password_key` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `new_password_requested` DATETIME NULL DEFAULT NULL,
  `new_email` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `new_email_key` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `last_ip` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `last_login` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `permisos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(30) NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  `restringido` TINYINT(1) NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `permisos_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `permisos_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `permiso_id` INT NULL,
  `usuario_id` INT NULL,
  `restriccion` VARCHAR(40) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `fechaHora` DATETIME NOT NULL,
  `tipoMovimiento` INT NOT NULL,
  `info` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `festivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `festivos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `fecha_UNIQUE` (`fecha` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `departamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `tipocontratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipocontratos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `estciviles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estciviles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `abreviatura` VARCHAR(4) NOT NULL,
  `descrip` VARCHAR(30) NULL,
  `trab1_desc0` TINYINT(1) NOT NULL,
  `colortexto` INT NOT NULL,
  `colorfondo` INT NOT NULL,
  `horainicio` TIME NULL,
  `horafin` TIME NULL,
  `visible` TINYINT(1) NULL DEFAULT TRUE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `abreviatura_UNIQUE` (`abreviatura` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `grupoestados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupoestados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `estados_grupoestados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estados_grupoestados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado_id` INT NULL,
  `grupoestado_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empleados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nif` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(150) NULL,
  `tlfnos` VARCHAR(30) NULL,
  `codpostal` VARCHAR(5) NULL,
  `poblacion` VARCHAR(30) NULL,
  `provincia` VARCHAR(30) NULL,
  `nacimiento` DATE NULL,
  `estcivil_id` INT NULL,
  `hijos` INT NULL,
  `nass` VARCHAR(15) NULL,
  `tarjeta` INT NULL,
  `observaciones` TEXT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT TRUE,
  `email` VARCHAR(128) NULL,
  `grupo` ENUM('AP','C2','C1','B','A2','A1') NULL DEFAULT 'AP',
  `antiguedad` DATE NULL,
  `siglas` VARCHAR(6) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `contratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contratos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comienzo` DATE NULL,
  `fin` DATE NULL,
  `fijeza` TINYINT(1) NOT NULL,
  `observaciones` TEXT NULL,
  `tipocontrato_id` INT NOT NULL,
  `empleado_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `puestos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puestos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comienzo_c` DATE NOT NULL,
  `fin_c` DATE NULL,
  `hastafin` TINYINT(1) NOT NULL,
  `categoria_id` INT NOT NULL,
  `departamento_id` INT NOT NULL,
  `contrato_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `cuadrantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuadrantes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `departamento_id` INT NULL,
  `anio` INT NULL,
  `initurno2d1t` INT NULL,
  `initurno3d1t` INT NULL,
  `initurno2d1t_3` INT NULL,
  `visible` TINYINT(1) NULL DEFAULT TRUE,
  `guardia` TINYINT(1) NULL DEFAULT TRUE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `cuadrantes_empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuadrantes_empleados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cuadrante_id` INT NOT NULL,
  `empleado_id` INT NOT NULL,
  `posicion` INT NULL,
  `tipoturno` INT NULL,
  `subturno` INT NULL,
  `visible` TINYINT(1) NOT NULL DEFAULT TRUE,
  `estadoT` INT NOT NULL DEFAULT 1,
  `estadoFST` INT NOT NULL,
  `estadoTN` INT NOT NULL,
  `estadoFSTN` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `asignaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asignaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `ini0_mod1` TINYINT(1) NULL,
  `empleado_id` INT NOT NULL,
  `cuadrante_id` INT NOT NULL,
  `estado_id` INT NOT NULL,
  `observaciones` TEXT NULL,
  `vinculo` VARCHAR(70) NULL,
  `incidencia` VARCHAR(150) NULL,
  `horaini` TIME NULL,
  `horafin` TIME NULL,
  `cronosini` TIME NULL,
  `cronosfin` TIME NULL,
  `cronossolved` TINYINT(1) NULL,
  `cronosinfo` VARCHAR(50) NULL,
  `cronosinfohoras` TIME NULL,
  `cronosobs` VARCHAR(100) NULL,
  `cronosinimod` TIME NULL,
  `cronosfinmod` TIME NULL,
  PRIMARY KEY (`id`),
  INDEX `ind_asignaciones` (`ini0_mod1` ASC, `cuadrante_id` ASC, `empleado_id` ASC, `fecha` ASC),
  INDEX `ind_estados` (`ini0_mod1` ASC, `estado_id` ASC),
  INDEX `ind_incidencias` (`ini0_mod1` ASC, `incidencia` ASC, `fecha` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `keywords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `keywords` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `anuncios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anuncios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `cuerpo` TEXT NULL,
  `fecha` DATETIME NOT NULL,
  `fechavalidez` DATETIME NOT NULL,
  `tablon_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `tablones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tablones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `visible` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `anuncioadjuntos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anuncioadjuntos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `anuncio_id` INT NOT NULL,
  `vinculo` VARCHAR(128) NOT NULL,
  `descrip` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `pcslentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcslentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(15) NOT NULL,
  `descrip` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `tareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tareas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `ubicacion` VARCHAR(50) NOT NULL,
  `descrip` TEXT NOT NULL,
  `fecha` DATE NOT NULL,
  `prioridad` INT NOT NULL,
  `prioridadactual` INT NOT NULL,
  `aumentoprioridad` TINYINT(1) NOT NULL,
  `visible` TINYINT(1) NOT NULL,
  `anulado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `departamentos_tareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `departamentos_tareas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `departamento_id` INT NOT NULL,
  `tarea_id` INT NOT NULL,
  `estadorealizacion` ENUM('enproceso','realizado','irrealizable') NOT NULL,
  `fechafin` DATE NULL,
  `empleado_id` INT NOT NULL,
  `cometido` VARCHAR(100) NOT NULL,
  `observaciones` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `adjuntostareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adjuntostareas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tarea_id` INT NOT NULL,
  `descrip` VARCHAR(45) NOT NULL,
  `vinculo` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `configuraciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `configuraciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `valor` VARCHAR(50) NOT NULL,
  `contenido` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `busquedas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `busquedas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `grupobusqueda_id` INT NOT NULL,
  `condicion` INT NOT NULL,
  `campo` VARCHAR(45) NOT NULL,
  `desccampo` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `texto` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `entradassalidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entradassalidas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(20) NULL,
  `fecha` DATE NULL,
  `fechadoc` DATE NULL,
  `orden` INT NULL,
  `anio` INT NULL,
  `remdest` VARCHAR(100) NULL,
  `clasedocumento_id` INT NULL,
  `contenido` VARCHAR(100) NULL,
  `observaciones` TEXT NULL,
  `resuelto` TINYINT(1) NULL,
  `pendiente` TINYINT(1) NOT NULL,
  `vinculo` VARCHAR(255) NOT NULL,
  `apuntado` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `ind_anio` (`anio` ASC, `orden` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `relacionesentradasalida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relacionesentradasalida` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `primero_id` INT NOT NULL,
  `segundo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ind_primero` (`primero_id` ASC, `segundo_id` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `procdestenv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `procdestenv` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NULL,
  `tipo` ENUM('ent_procedencia','ent_destino','sal_destino','sal_enviador') NULL,
  `visible` TINYINT(1) NULL DEFAULT FALSE,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `entradassalidas_procdestenv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entradassalidas_procdestenv` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `procdestenv_id` INT NOT NULL,
  `entradasalida_id` INT NOT NULL,
  `tipo` ENUM('ent_procedencia','ent_destino','sal_destino','sal_enviador') NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `huecosentradasalida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `huecosentradasalida` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `anio` INT NOT NULL,
  `tipo` VARCHAR(7) NOT NULL,
  `hueco` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `clasesdocumentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clasesdocumentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `visible` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `empleados_entradassalidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empleados_entradassalidas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empleado_id` INT NOT NULL,
  `entradasalida_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `bolsas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolsas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `bolsasempleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolsasempleados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empleado_id` INT NOT NULL,
  `bolsa_id` INT NOT NULL,
  `inscripcion` ENUM('acompensar','acobrar','ambas') NOT NULL DEFAULT 'ambas',
  `suma_acompensar` INT NOT NULL,
  `suma_acobrar` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `trabajoshhee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabajoshhee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lugar` VARCHAR(75) NOT NULL,
  `descrip` VARCHAR(100) NOT NULL,
  `ini` DATETIME NOT NULL,
  `fin` DATETIME NOT NULL,
  `formacobro` ENUM('acompensar','acobrar','arecuperar','ambas') NOT NULL DEFAULT 'acompensar',
  `concejalia_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `empleados_trabajoshhee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empleados_trabajoshhee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empleado_id` INT NOT NULL,
  `trabajohhee_id` INT NOT NULL,
  `ini` DATETIME NOT NULL,
  `fin` DATETIME NOT NULL,
  `fechavalor` DATE NOT NULL,
  `formacobro` ENUM('acompensar','acobrar','arecuperar') NOT NULL,
  `compensadasnormales` INT NOT NULL,
  `compensadasfestivas` INT NOT NULL,
  `fechatope` DATE NOT NULL,
  `normales` INT NOT NULL,
  `nocturnas` INT NOT NULL,
  `festivas` INT NOT NULL,
  `festivasnoct` INT NOT NULL,
  `precionormales` DOUBLE NOT NULL,
  `precionocturnas` DOUBLE NOT NULL,
  `preciofestivas` DOUBLE NOT NULL,
  `preciofestivasnoct` DOUBLE NOT NULL,
  `preciototal` DOUBLE NOT NULL,
  `parteasociado` INT NULL,
  `totalrealizadas` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `negaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empleado_id` INT NOT NULL,
  `ini` DATETIME NOT NULL,
  `fin` DATETIME NOT NULL,
  `total` INT NOT NULL,
  `lugar` VARCHAR(100) NOT NULL,
  `trabajo` VARCHAR(150) NOT NULL,
  `obs` VARCHAR(150) NOT NULL,
  `usuario_id` INT NOT NULL,
  `fechahora` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `empleados` (`empleado_id` ASC, `ini` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `descansos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `descansos` (
  `id` INT NOT NULL,
  `empleado_id` INT NOT NULL,
  `anio` INT NOT NULL,
  `tipo` ENUM('vacaciones','aapp','sabados','navidad','semanasanta','puente') NOT NULL,
  `tiemposegundos` INT NOT NULL,
  `tipotiempo` ENUM('dias','horas') NOT NULL,
  `dias_horas` INT NOT NULL,
  `minutos` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `grupobusquedas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupobusquedas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `descrip` VARCHAR(50) NOT NULL,
  `tabla` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `txtsinfocronos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `txtsinfocronos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `resumenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resumenes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('nocturnidad','turnicidad') NOT NULL,
  `mes` INT NOT NULL,
  `anio` INT NOT NULL,
  `cantidad` DOUBLE NOT NULL,
  `descrip` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `certificacion` INT NULL,
  `proveedor` VARCHAR(70) NULL,
  `fechaFra` DATETIME NULL,
  `nroFra` VARCHAR(25) NULL,
  `importe` DOUBLE(15,5) NULL,
  `descrip` VARCHAR(255) NULL,
  `vinculo` VARCHAR(255) NULL,
  `conforme` TINYINT(1) NOT NULL,
  `contestada` TINYINT(1) NOT NULL,
  `fechaRecepcion` DATETIME NULL,
  `persona` VARCHAR(45) NULL,
  `cantidadPagada` DOUBLE NOT NULL,
  `presupuesto_id` INT NULL,
  `formaPago` SET('transferencia','contador') NOT NULL DEFAULT transferencia,
  PRIMARY KEY (`id`),
  INDEX `Ind_FechaFra` (`proveedor` ASC, `nroFra` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 2290
COMMENT = '				';


-- -----------------------------------------------------
-- Table `presupuestos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `presupuestos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `proveedor` VARCHAR(70) NOT NULL,
  `nro` VARCHAR(20) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `importe` DOUBLE NOT NULL,
  `descripcion` TEXT NULL,
  `conforme` TINYINT(1) NULL DEFAULT 0,
  `trabajado` TINYINT(1) NULL DEFAULT 0,
  `suministrado` TINYINT(1) NULL DEFAULT 0,
  `vinculo` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 3;


-- -----------------------------------------------------
-- Table `informesfras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `informesfras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `orden` INT NULL,
  `fecha` DATETIME NULL,
  `anio` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `Ind_orden` (`anio` ASC, `orden` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 352;


-- -----------------------------------------------------
-- Table `facturas_informesfras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturas_informesfras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `factura_id` INT NOT NULL,
  `informefra_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 883;


-- -----------------------------------------------------
-- Table `cambiosasignaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cambiosasignaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `ini0_mod1` TINYINT(1) NULL,
  `empleado_id` INT NOT NULL,
  `cuadrante_id` INT NOT NULL,
  `estadoini` INT NOT NULL,
  `estadofin` INT NOT NULL,
  `fechacambio` DATETIME NOT NULL,
  `usuario_id` INT NOT NULL,
  `enviadoemail` TINYINT(1) NULL,
  `anotadoCP` TINYINT(1) NULL,
  `obsini` TEXT NULL,
  `incicini` VARCHAR(150) NULL,
  `horainiini` TIME NULL,
  `horafinini` TIME NULL,
  PRIMARY KEY (`id`),
  INDEX `ind_asignaciones` (`ini0_mod1` ASC, `cuadrante_id` ASC, `empleado_id` ASC, `fecha` ASC),
  INDEX `ind_estados` (`ini0_mod1` ASC, `estadoini` ASC),
  INDEX `ind_incidencias` (`ini0_mod1` ASC, `fecha` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `concejalias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concejalias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `vinculosES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinculosES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `entradasalida_id` INT NOT NULL,
  `vinculo` VARCHAR(255) NOT NULL,
  `descrip` VARCHAR(100) NOT NULL,
  `orden` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `almacenarticulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacenarticulos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `familia` VARCHAR(5) NOT NULL,
  `codigo` VARCHAR(10) NOT NULL,
  `descrip` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `almacenusers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacenusers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(11) NOT NULL,
  `almacendepartamento_id` INT(11) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `tlf` VARCHAR(45) NULL,
  `perfil` SET('peticionario', 'admon', 'responsable', 'almacen', 'usuarios') NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `almacendepartamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacendepartamentos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descrip` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `almacenpedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacenpedidos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `anio` INT(11) NOT NULL,
  `nro` INT(11) NOT NULL,
  `descrip` VARCHAR(60) NULL,
  `estado` ENUM('tramite', 'aceptado', 'rechazado', 'solicitado', 'rec_parc', 'rec_total', 'ent_parc', 'ent_total') NOT NULL DEFAULT 'tramite' COMMENT 'tramite: cuando se inicia, aceptado: vºbº de admon y responsable, rechazado: ha sido rechazado por admon o responsable, solicitado: pedido por el almacén, rec_parc: recibido parcialmente en el almacén, rec_total: recibido en su totalidad en el almacé' /* comment truncated */ /*n, ent_parc: entregado parcialmente a su peticionario, ent_total: entregado totalmente a su peticionario*/,
  `razonrechazo` VARCHAR(45) NULL COMMENT 'refleja rechazo dependiendo del paso de trámite en el que esté',
  `pasotramite` ENUM('admon', 'responsable', 'almacen', 'ninguno') NOT NULL DEFAULT 'ninguno' COMMENT 'admon, responsable, almacen, ninguno',
  `fechatramite` DATETIME NOT NULL,
  `fechaaceptado` DATETIME NULL,
  `fechasolicitado` DATETIME NULL,
  `fecharecparc` DATETIME NULL,
  `fecharectotal` DATETIME NULL,
  `fechaentparc` DATETIME NULL,
  `fechaenttotal` DATETIME NULL,
  `fecharechazado` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `almacenarticulospedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacenarticulospedidos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `almacenpedido_id` INT(11) NOT NULL,
  `familia` VARCHAR(5) NULL,
  `codigo` VARCHAR(10) NULL,
  `descrip` VARCHAR(100) NOT NULL,
  `unds` DOUBLE NOT NULL,
  `estadoadmonalmacen` ENUM('tramite', 'aceptado', 'reparo') NOT NULL DEFAULT 'tramite' COMMENT 'tramite: recibido y en trámite, aceptado: correcto para pedir, reparo: no pedir por alguna razón',
  `estadoresponsable` ENUM('tramite', 'aceptado', 'rechazado') NOT NULL DEFAULT 'tramite' COMMENT 'tramite: recibido y en trámite, aceptado: correcto para pedir, rechazado: no pedir por alguna razón',
  `estadoalmacen` ENUM('tramite', 'rechazado', 'solicitado', 'rec_parc', 'rec_total', 'ent_parc', 'ent_total') NOT NULL DEFAULT 'tramite' COMMENT 'tramite: recibido y en trámite, rechazado: no pedido por alguna razón, solicitado: pedido a proveedor, rec_parc: recibido parcialmente, rec_total: recibido totalmente, ent_parc: entregado parcialmente, ent_total: entregado totalmente',
  `razonreparoadmonalmacen` VARCHAR(45) NULL,
  `razonrechazoresponsable` VARCHAR(45) NULL,
  `razonrechazoalmacen` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `almacenpedidos_almacenusers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacenpedidos_almacenusers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `almacenpedido_id` INT(11) NOT NULL,
  `almacenusuario_id` INT(11) NOT NULL,
  `peticionario` TINYINT(1) NOT NULL DEFAULT 0,
  `notificar` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `almacenfamilias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacenfamilias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(5) NOT NULL,
  `descrip` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `hheecronos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hheecronos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `fecha` DATE NOT NULL,
  `ini` TIME NOT NULL,
  `fin` TIME NOT NULL,
  `automatico` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Indicativo de si el parte de este horario ha sido generado automaticamente',
  PRIMARY KEY (`id`),
  INDEX `index_trab_fecha` (`nombre` ASC, `fecha` ASC, `ini` ASC, `fin` ASC),
  INDEX `index_fecha_trab` (`fecha` ASC, `ini` ASC, `fin` ASC, `nombre` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `cvusers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvusers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `observaciones` VARCHAR(2555) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `cvorganismos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvorganismos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `cvestadosactuaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvestadosactuaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cvestadosactuacionescol` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `cvactuaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvactuaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nro` VARCHAR(45) NOT NULL,
  `cvuser_id` INT NOT NULL,
  `descripcion` VARCHAR(50) NULL,
  `cvcalle_id` INT NULL,
  `calle_obsoleta` VARCHAR(50) NULL,
  `nro_calle` VARCHAR(100) NULL,
  `nroTAO` INT NULL,
  `inicio` DATE NULL,
  `fin` DATE NULL,
  `cvestadosactuacion_id` INT NOT NULL,
  `cvorganismo_id` INT NULL,
  `observaciones` TEXT NULL,
  `vinculos` INT(11) NOT NULL DEFAULT 0,
  `prioridad` VARCHAR(5) NULL DEFAULT 'MEDIA',
  `anio` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `cvvinculosactuaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvvinculosactuaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cvactuacion_id` INT NOT NULL,
  `descrip` VARCHAR(100) NOT NULL,
  `imagen` TINYINT(1) NOT NULL DEFAULT 1,
  `orden` INT NOT NULL DEFAULT 0,
  `ext` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gppartes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gppartes` (
  `id` INT NOT NULL,
  `cvactuacion_id` INT NULL,
  `gporigen_id` VARCHAR(45) NOT NULL,
  `nroTAO` INT NULL,
  `gpestados` ENUM('pendiente', 'parcial', 'terminado', 'visado') NOT NULL,
  `fecha` DATE NOT NULL,
  `prioridad` VARCHAR(5) NOT NULL,
  `descrip` TEXT NOT NULL,
  `obs` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gporigenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gporigenes` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `tipo` ENUM('servicio', 'chat_verde', 'tao', 'email') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gpdestinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpdestinos` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `departamentos_gppartes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `departamentos_gppartes` (
  `id` INT NOT NULL,
  `gpparte_id` INT NOT NULL,
  `departamento_id` INT NOT NULL,
  `estado` ENUM('pendiente', 'terminado', 'rechazado', 'visado') NOT NULL DEFAULT 'pendiente',
  `obs` VARCHAR(255) NULL,
  `visto` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gpdestinos_gppartes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpdestinos_gppartes` (
  `id` INT NOT NULL,
  `gpdestino_id` INT NOT NULL,
  `gpparte_id` INT NOT NULL,
  `visto` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gpusers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpusers` (
  `id` INT NOT NULL,
  `usuario_id` INT(11) NOT NULL,
  `supervisor` TINYINT(1) NOT NULL DEFAULT 0,
  `departamento_id` INT NULL COMMENT 'Nulo significa que no esta adherido a ningun departamento',
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gpdestinos_gpusers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpdestinos_gpusers` (
  `id` INT NOT NULL,
  `gpdestino_id` INT NOT NULL,
  `gpuser_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `cvhuecosactuaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvhuecosactuaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `anio` INT NOT NULL,
  `hueco` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `arqcalles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arqcalles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descrip` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `arqempresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arqempresas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descrip` VARCHAR(100) NOT NULL,
  `color` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `arqestados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arqestados` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descrip` VARCHAR(100) NOT NULL,
  `color` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `arquetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arquetas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `arqcalle_id` INT(11) NOT NULL,
  `anotacion` VARCHAR(100) NULL,
  `gps` VARCHAR(100) NULL,
  `incidencia` BLOB NULL,
  `expte` VARCHAR(100) NULL,
  `arqempresa_id` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `arqadjuntos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arqadjuntos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `arqueta_id` INT(11) NOT NULL,
  `descrip` VARCHAR(100) NOT NULL,
  `ext` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `arqestados_arquetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arqestados_arquetas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `arqestado_id` INT(11) NOT NULL,
  `arqueta_id` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `user_profiles`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `user_profiles` (`id`, `user_id`, `country`, `website`) VALUES (1, 1, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `users`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `users` (`id`, `username`, `password`, `email`, `activated`, `banned`, `ban_reason`, `new_password_key`, `new_password_requested`, `new_email`, `new_email_key`, `last_ip`, `last_login`, `created`, `modified`) VALUES (1, 'admin', '$P$BEv1.ggt4R.vd1GL7wqYKN4Vf1Ikzp0', 'admin@dominio.com', 1, 0, '', '', '', NULL, NULL, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `estados`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `estados` (`id`, `abreviatura`, `descrip`, `trab1_desc0`, `colortexto`, `colorfondo`, `horainicio`, `horafin`, `visible`) VALUES (DEFAULT, 'T', 'Trabajo', 1, 0, 2589947, NULL, NULL, NULL);
INSERT INTO `estados` (`id`, `abreviatura`, `descrip`, `trab1_desc0`, `colortexto`, `colorfondo`, `horainicio`, `horafin`, `visible`) VALUES (DEFAULT, 'D', 'Descanso', 0, 0, 7798646, NULL, NULL, NULL);
INSERT INTO `estados` (`id`, `abreviatura`, `descrip`, `trab1_desc0`, `colortexto`, `colorfondo`, `horainicio`, `horafin`, `visible`) VALUES (DEFAULT, 'FSD', 'Fin de semana descansado', 0, 0, 7798646, NULL, NULL, NULL);
INSERT INTO `estados` (`id`, `abreviatura`, `descrip`, `trab1_desc0`, `colortexto`, `colorfondo`, `horainicio`, `horafin`, `visible`) VALUES (DEFAULT, 'FST', 'Fin de semana trabajado', 1, 0, 2589947, NULL, NULL, NULL);
INSERT INTO `estados` (`id`, `abreviatura`, `descrip`, `trab1_desc0`, `colortexto`, `colorfondo`, `horainicio`, `horafin`, `visible`) VALUES (DEFAULT, 'GU', 'Guardia', 1, 0, 2589947, NULL, NULL, NULL);
INSERT INTO `estados` (`id`, `abreviatura`, `descrip`, `trab1_desc0`, `colortexto`, `colorfondo`, `horainicio`, `horafin`, `visible`) VALUES (DEFAULT, 'TT', 'Trabajo de tarde', 1, 0, 2589947, NULL, NULL, NULL);
INSERT INTO `estados` (`id`, `abreviatura`, `descrip`, `trab1_desc0`, `colortexto`, `colorfondo`, `horainicio`, `horafin`, `visible`) VALUES (DEFAULT, 'TN', 'Trabajo de noche', 1, 0, 2589947, NULL, NULL, NULL);
INSERT INTO `estados` (`id`, `abreviatura`, `descrip`, `trab1_desc0`, `colortexto`, `colorfondo`, `horainicio`, `horafin`, `visible`) VALUES (DEFAULT, 'FSTT', 'Fin de semana trab. tarde', 1, 0, 2589947, NULL, NULL, NULL);
INSERT INTO `estados` (`id`, `abreviatura`, `descrip`, `trab1_desc0`, `colortexto`, `colorfondo`, `horainicio`, `horafin`, `visible`) VALUES (DEFAULT, 'FSTN', 'Fin se semana trab. noche', 1, 0, 2589947, NULL, NULL, NULL);
INSERT INTO `estados` (`id`, `abreviatura`, `descrip`, `trab1_desc0`, `colortexto`, `colorfondo`, `horainicio`, `horafin`, `visible`) VALUES (DEFAULT, 'HC', 'Horas extras a comp.', 1, 0, 7798646, NULL, NULL, NULL);
INSERT INTO `estados` (`id`, `abreviatura`, `descrip`, `trab1_desc0`, `colortexto`, `colorfondo`, `horainicio`, `horafin`, `visible`) VALUES (DEFAULT, 'DC', 'Día a comp. por HHEE', 0, 0, 7798646, NULL, NULL, NULL);
INSERT INTO `estados` (`id`, `abreviatura`, `descrip`, `trab1_desc0`, `colortexto`, `colorfondo`, `horainicio`, `horafin`, `visible`) VALUES (DEFAULT, 'AP', 'Asuntos particulares', 0, 0, 7798646, NULL, NULL, NULL);
INSERT INTO `estados` (`id`, `abreviatura`, `descrip`, `trab1_desc0`, `colortexto`, `colorfondo`, `horainicio`, `horafin`, `visible`) VALUES (DEFAULT, 'HAP', 'Horas de Asuntos part.', 1, 0, 2589947, NULL, NULL, NULL);
INSERT INTO `estados` (`id`, `abreviatura`, `descrip`, `trab1_desc0`, `colortexto`, `colorfondo`, `horainicio`, `horafin`, `visible`) VALUES (DEFAULT, 'AAP', 'Asuntos Año pasado', 0, 0, 7798646, NULL, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `concejalias`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `concejalias` (`id`, `nombre`) VALUES (1, 'Servicios Operativos');
INSERT INTO `concejalias` (`id`, `nombre`) VALUES (2, 'Festejos');
INSERT INTO `concejalias` (`id`, `nombre`) VALUES (3, 'Bienestar Social');
INSERT INTO `concejalias` (`id`, `nombre`) VALUES (4, 'Educación');
INSERT INTO `concejalias` (`id`, `nombre`) VALUES (5, 'Cultura');

COMMIT;

